(()=>{
const P=window.EQUARROW_PUZZLES;if(!P)return;const q=new URLSearchParams(location.search),x=q.get('p')||'004',id=P[x]?x:'004',p=P[id],enabled=p.difficulty!=='Easy';
const T={en:{a:'Notes',b:'Know only one half of an arrow? Add a note.',c:'How notes work',d:'Use notes when you know only one half of an arrow. Tap ← or → for its horizontal direction, or ↑ or ↓ for its vertical direction. When both halves are known, EQUARROW automatically converts them into the matching diagonal arrow.'},pl:{a:'Notatki',b:'Znasz tylko połowę kierunku strzałki? Dodaj notatkę.',c:'Jak używać notatek',d:'Używaj notatek, gdy znasz tylko jedną część kierunku strzałki. Dotknij ← lub → dla kierunku poziomego albo ↑ lub ↓ dla pionowego. Gdy znane są obie części, EQUARROW automatycznie zamieni je na właściwą strzałkę po przekątnej.'},es:{a:'Notas',b:'¿Solo conoces una parte de la flecha? Añade una nota.',c:'Cómo usar las notas',d:'Usa las notas cuando solo conozcas una parte de la dirección de una flecha. Toca ← o → para la dirección horizontal, o ↑ o ↓ para la vertical. Cuando conozcas ambas partes, EQUARROW las convertirá automáticamente en la flecha diagonal correspondiente.'},de:{a:'Notizen',b:'Kennst du nur eine Hälfte des Pfeils? Setze eine Notiz.',c:'So funktionieren Notizen',d:'Nutze Notizen, wenn du nur eine Richtungshälfte eines Pfeils kennst. Tippe ← oder → für die horizontale Richtung und ↑ oder ↓ für die vertikale. Sobald beide Hälften feststehen, wandelt EQUARROW sie automatisch in den passenden diagonalen Pfeil um.'},fr:{a:'Notes',b:'Vous ne connaissez qu’une moitié de la flèche ? Ajoutez une note.',c:'Comment utiliser les notes',d:'Utilisez les notes lorsque vous ne connaissez qu’une partie de la direction d’une flèche. Touchez ← ou → pour la direction horizontale, ou ↑ ou ↓ pour la verticale. Lorsque les deux parties sont connues, EQUARROW les transforme automatiquement en la flèche diagonale correspondante.'}};
function tr(){const s=document.querySelector('[data-language-select]'),l=((s&&s.value)||document.documentElement.lang||'en').slice(0,2);return T[l]||T.en}
const board=document.getElementById('board'),status=document.getElementById('status'),section=document.getElementById('notesSection'),state=Array.from({length:16},()=>({h:'',v:''}));
function cs(){return [...board.querySelectorAll('.cell')]}function si(){return cs().findIndex(c=>c.classList.contains('selected'))}function clear(i){if(i>=0)state[i]={h:'',v:''}}function mark(n){return n.h==='L'?'←':n.h==='R'?'→':n.v==='U'?'↑':n.v==='D'?'↓':''}
function draw(){const cells=cs();cells.forEach(c=>c.querySelectorAll('.cell-note').forEach(e=>e.remove()));state.forEach((n,i)=>{const c=cells[i],m=mark(n);if(!c||!m||c.classList.contains('given')||c.textContent.trim())return;const e=document.createElement('span');e.className='cell-note';e.textContent=m;c.appendChild(e)})}
if(board)new MutationObserver(()=>queueMicrotask(draw)).observe(board,{childList:true});document.querySelectorAll('.pick').forEach(b=>b.addEventListener('click',()=>{clear(si());queueMicrotask(draw)},true));document.getElementById('reset')?.addEventListener('click',()=>state.forEach((_,i)=>clear(i)),true);
document.querySelectorAll('.note-pick').forEach(b=>b.onclick=()=>{const i=si();if(i<0){status.textContent='Select a square';return}const cell=cs()[i];if(!cell||cell.classList.contains('given'))return;if(cell.textContent.trim()&&!cell.querySelector('.cell-note'))document.querySelector('.pick[data-d=""]')?.click();const n=state[i],v=b.dataset.note;if(v==='L'||v==='R')n.h=n.h===v?'':v;else n.v=n.v===v?'':v;if(n.h&&n.v){const d={LU:'NW',LD:'SW',RU:'NE',RD:'SE'}[n.h+n.v];clear(i);document.querySelector(`.pick[data-d="${d}"]`)?.click()}else draw()});
function labels(){section.hidden=!enabled;if(!enabled)return;const z=tr();document.getElementById('notesTitle').textContent=z.a;document.getElementById('notesHint').textContent=z.b;document.getElementById('notesSummary').textContent=z.c;document.getElementById('notesHelpText').textContent=z.d}document.addEventListener('equarrow-language-change',labels);labels();draw();
})();